const restList = [
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "361866",
        name: "Peetuk",
        uuid: "21e145d0-9fd2-4682-97cc-4286ca9214db",
        city: "1",
        area: "Domlur",
        totalRatingsString: "",
        cloudinaryImageId: "mjbyg3ph9jsh0b6d3mwm",
        cuisines: ["Bengali", "Chinese"],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        slaString: "27 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "peetuk-indiranagar-indiranagar-2",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "7th Cross",
        parentId: 1668,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 3900,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3900,
          message: "",
          title: "Delivery Charge",
          amount: "3900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7327167~p=1~eid=00000189-6db1-5092-1d84-90a300e9016e~srvts=1689762484370~83649",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.5 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=361866&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 27,
          minDeliveryTime: 27,
          maxDeliveryTime: 27,
          lastMileTravel: 0,
          lastMileDistance: 4.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "42060",
        name: "Sharief Bhai",
        uuid: "7c8f6e06-2306-458b-a172-a7ba9e906ae9",
        city: "1",
        area: "Koramangala",
        totalRatingsString: "",
        cloudinaryImageId: "mmavnrootu7ypscic1qm",
        cuisines: [
          "Biryani",
          "Mughlai",
          "Arabian",
          "Kebabs",
          "Desserts",
          "Beverages",
        ],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 20,
        minDeliveryTime: 20,
        maxDeliveryTime: 20,
        slaString: "20 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "sharief-bhai-koramangala-koramangala",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Koramangala",
        parentId: 5734,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 2700,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2700,
          message: "",
          title: "Delivery Charge",
          amount: "2700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7493536~p=2~eid=00000189-6db1-5092-1d84-90a400e90247~srvts=1689762484370~83649",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.6 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=42060&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 20,
          minDeliveryTime: 20,
          maxDeliveryTime: 20,
          lastMileTravel: 0,
          lastMileDistance: 1.6,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "18973",
        name: "Nandhana Palace",
        uuid: "2beb785e-2aeb-4b83-afb4-efffcb7301ca",
        city: "1",
        area: "Koramangala 4-B Block",
        totalRatingsString: "",
        cloudinaryImageId: "195876a3181ef63f76e45e3a7b49b585",
        cuisines: ["Biryani", "Andhra", "South Indian", "North Indian"],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 14,
        minDeliveryTime: 14,
        maxDeliveryTime: 14,
        slaString: "14 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "nandhana-palace-koramangala-koramangala",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Koramangala",
        parentId: 2120,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 2700,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2700,
          message: "",
          title: "Delivery Charge",
          amount: "2700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7492290~p=3~eid=00000189-6db1-5092-1d84-90a500e90340~srvts=1689762484370~83649",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.6 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=18973&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 14,
          minDeliveryTime: 14,
          maxDeliveryTime: 14,
          lastMileTravel: 0,
          lastMileDistance: 0.6,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "387335",
        name: "Biryani By Kilo",
        uuid: "785434d0-4b9e-4eac-8936-2ad70efb39c1",
        city: "1",
        area: "Koramangala",
        totalRatingsString: "",
        cloudinaryImageId: "c0h0oillrhcdff9tp9qm",
        cuisines: [
          "Biryani",
          "Hyderabadi",
          "North Indian",
          "Kebabs",
          "Mughlai",
          "Desserts",
        ],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        slaString: "30 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "biryani-by-kilo-koramangala-koramangala",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "6th Block",
        parentId: 130,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 2700,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2700,
          message: "",
          title: "Delivery Charge",
          amount: "2700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7493090~p=5~eid=00000189-6db1-5092-1d84-90a700e90514~srvts=1689762484370~83649",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.1 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=387335&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          lastMileTravel: 0,
          lastMileDistance: 0.1,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.0",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "340645",
        name: "RNR Biryani - Taste of 1953",
        uuid: "d6bed3ab-d2a7-4926-ba9a-93c32e9e0197",
        city: "1",
        area: "Koramangala",
        totalRatingsString: "",
        cloudinaryImageId: "jhdven0c7dkmypffoigf",
        cuisines: ["Biryani", "South Indian", "Kebabs"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 15,
        minDeliveryTime: 15,
        maxDeliveryTime: 15,
        slaString: "15 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "rnr-biryani---taste-of-1953-koramangala-koramangala",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "4th B Block",
        parentId: 11620,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 2700,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2700,
          message: "",
          title: "Delivery Charge",
          amount: "2700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7492335~p=7~eid=00000189-6db1-5092-1d84-90a900e9077f~srvts=1689762484370~83649",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.6 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=340645&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 15,
          minDeliveryTime: 15,
          maxDeliveryTime: 15,
          lastMileTravel: 0,
          lastMileDistance: 0.6,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "3454",
        name: "Lazeez",
        uuid: "2560907d-0989-406a-9815-fe0002719106",
        city: "1",
        area: "Koramangala",
        totalRatingsString: "",
        cloudinaryImageId: "use18ykhj8llbdohba6e",
        cuisines: ["North Indian", "Mughlai"],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 18,
        minDeliveryTime: 18,
        maxDeliveryTime: 18,
        slaString: "18 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "lazeez-koramangala-2",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "5th Block",
        parentId: 588,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 2700,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2700,
          message: "",
          title: "Delivery Charge",
          amount: "2700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=3454&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 18,
          minDeliveryTime: 18,
          maxDeliveryTime: 18,
          lastMileTravel: 0,
          lastMileDistance: 1,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "292770",
        name: "Charminar Biryani House",
        uuid: "ebc48003-1dbd-4fca-8dd0-740cc4413310",
        city: "1",
        area: "BTM Layout",
        totalRatingsString: "",
        cloudinaryImageId: "l8z0w7mrwwlkky0tumgv",
        cuisines: ["Biryani", "North Indian"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: "24 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "charminar\tbiriyani\thouse-btm-btm",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "1st  Stage",
        parentId: 58180,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 3300,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3300,
          message: "",
          title: "Delivery Charge",
          amount: "3300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.5 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=292770&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 0,
          lastMileDistance: 3.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "229",
        name: "Meghana Foods",
        uuid: "4fdd19e2-5d0f-4bde-9c7f-dc3e8d36021f",
        city: "1",
        area: "Koramangala",
        totalRatingsString: "",
        cloudinaryImageId: "xqwpuhgnsaf18te7zvtv",
        cuisines: [
          "Biryani",
          "Andhra",
          "South Indian",
          "North Indian",
          "Chinese",
          "Seafood",
        ],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 14,
        minDeliveryTime: 14,
        maxDeliveryTime: 14,
        slaString: "14 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "meghana-foods-5th-block-koramangala",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "5th Block",
        parentId: 635,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 2700,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2700,
          message: "",
          title: "Delivery Charge",
          amount: "2700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.4 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=229&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 14,
          minDeliveryTime: 14,
          maxDeliveryTime: 14,
          lastMileTravel: 0,
          lastMileDistance: 1.4,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "131864",
        name: "Kerala Food Club",
        uuid: "599369d2-8c19-4ac9-b662-d34a83ec2259",
        city: "1",
        area: "Bommanahalli",
        totalRatingsString: "",
        cloudinaryImageId: "vslvkkwgt82r4hcazebu",
        cuisines: ["Kerala", "Chinese", "Biryani", "Seafood", "South Indian"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        slaString: "23 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "kerala-food-club-koramangala",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "House Road",
        parentId: 21345,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 2700,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2700,
          message: "",
          title: "Delivery Charge",
          amount: "2700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.1 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=131864&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 23,
          minDeliveryTime: 23,
          maxDeliveryTime: 23,
          lastMileTravel: 0,
          lastMileDistance: 2.1,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "252782",
        name: "Aramane Donne Biriyani",
        uuid: "39f8f363-186a-4be8-8fdd-e5ea5d788fc0",
        city: "1",
        area: "Koramangala",
        totalRatingsString: "",
        cloudinaryImageId: "bqzix8f33km3nvqtn2uz",
        cuisines: ["Indian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 18,
        minDeliveryTime: 18,
        maxDeliveryTime: 18,
        slaString: "18 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "aramane-donne-biriyani-koramangala-koramangala",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "8th Block",
        parentId: 7133,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 2700,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2700,
          message: "",
          title: "Delivery Charge",
          amount: "2700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.4 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=252782&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 18,
          minDeliveryTime: 18,
          maxDeliveryTime: 18,
          lastMileTravel: 0,
          lastMileDistance: 1.4,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "422917",
        name: "Hyderabad Magic",
        uuid: "f7f997c7-f3bf-4ce6-80a1-08f21da4e439",
        city: "1",
        area: "Bommanahalli",
        totalRatingsString: "",
        cloudinaryImageId: "vm7winbxdem0w9bssxqg",
        cuisines: ["Andhra", "Biryani"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        slaString: "30 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "hyderabad-magic-hsr-hsr",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Roopena Agrahara",
        parentId: 21606,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 3300,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3300,
          message: "",
          title: "Delivery Charge",
          amount: "3300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [
            {
              iconId: "guiltfree/GF_Logo_android_3x",
              description: "",
              shortDescription: "options available",
              fontColor: "#7E808C",
            },
          ],
        },
        lastMileTravelString: "3.8 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=422917&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          lastMileTravel: 0,
          lastMileDistance: 3.8,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "275",
        name: "Mani's Dum Biryani",
        uuid: "6a5627da-e918-431b-ae62-1c2da89324b1",
        city: "1",
        area: "Koramangala",
        totalRatingsString: "",
        cloudinaryImageId: "xlr4ngepa5gxkugrsdbs",
        cuisines: ["Andhra", "Biryani"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 18,
        minDeliveryTime: 18,
        maxDeliveryTime: 18,
        slaString: "18 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "manis-dum-biryani-jyoti-nivas-rd-5th-block-koramangala",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "Koramangala",
        parentId: 623,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 2700,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2700,
          message: "",
          title: "Delivery Charge",
          amount: "2700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.6 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=275&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 18,
          minDeliveryTime: 18,
          maxDeliveryTime: 18,
          lastMileTravel: 0,
          lastMileDistance: 1.6,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "642459",
        name: "Malnad Donne Biryani MDB",
        uuid: "4ae022a0-9296-40ac-8ea9-3e764200e6a5",
        city: "1",
        area: "Jayanagar",
        totalRatingsString: "",
        cloudinaryImageId: "tjw67zgzfehxgfo1vio2",
        cuisines: ["Biryani", "South Indian", "Kebabs"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        slaString: "28 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "malnad-donne-biryani-mdb-jayanagar-jayanagar",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "T Block",
        parentId: 130946,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 5200,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 5200,
          message: "",
          title: "Delivery Charge",
          amount: "5200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5.6 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=642459&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          lastMileTravel: 0,
          lastMileDistance: 5.6,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "58087",
        name: "Hiyar Majhe Kolkata",
        uuid: "b3b678aa-f66d-4736-95f2-75ac70e21ff5",
        city: "1",
        area: "BTM Layout",
        totalRatingsString: "",
        cloudinaryImageId: "bv32mh8oozkhj4fd5rxl",
        cuisines: ["North Indian", "Bengali", "Chinese", "Desserts"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        slaString: "28 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "hiyar-majhe-kolkata-btm-btm",
          city: "Bangalore",
        },
        cityState: "1",
        address: "",
        locality: "2nd Stage",
        parentId: 11208,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 5200,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 5200,
          message: "",
          title: "Delivery Charge",
          amount: "5200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5 kms",
        hasSurge: false,
        cta: {
          link: "swiggy://menu?restaurant_id=58087&source=collection&query=Biryani",
          type: "DEEPLINK",
          text: "RESTAURANT_MENU",
        },
        sla: {
          restaurantId: "",
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          lastMileTravel: 0,
          lastMileDistance: 5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
];

export default restList;
